// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package types

type ImageRequest struct {
}

type ImageResponse struct {
	Url string `json:"url"`
}

type ImageShowRequest struct {
	ImageType string `path:"imageType"`
	ImageName string `path:"imageName"`
}
