// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package types

type UserInfoRequest struct {
	UserID uint `header:"User-ID"`
	Role   int8 `header:"Role"`
}

type UserInfoResponse struct {
	UserID         uint   `json:"userID"`
	Nickname       string `json:"nickname"`
	Role           int8   `json:"role"`
	Abstract       string `json:"abstract"`
	Avatar         string `json:"avatar"`
	RegisterSource string `json:"registerSource"` // 注册来源
}
